ALTER TABLE VLANZ.EMPL_CAPA
 DROP PRIMARY KEY CASCADE;

DROP TABLE VLANZ.EMPL_CAPA CASCADE CONSTRAINTS;

CREATE TABLE VLANZ.EMPL_CAPA
(
  EMCA_ID       NUMBER(10)                      NOT NULL,
  EMCA_EMPL_ID  NUMBER(10)                      NOT NULL,
  EMCA_CAPA_ID  NUMBER(10)                      NOT NULL,
  EMCA_LEVEL    NUMBER(1)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX VLANZ.EMCA_UK_FKS ON VLANZ.EMPL_CAPA
(EMCA_EMPL_ID, EMCA_CAPA_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX VLANZ.EMPL_CAPA_PK ON VLANZ.EMPL_CAPA
(EMCA_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER VLANZ.EMCA_BIUR 
before insert ON VLANZ.EMPL_CAPA 
for each row
BEGIN
  :new.emca_id := nvl(:new.emca_id , emca_seq.nextval);
END;
/


ALTER TABLE VLANZ.EMPL_CAPA ADD (
  CONSTRAINT EMCA_LEVEL_CHK
  CHECK (emca_level in (0,1,2,3,4,5))
  ENABLE VALIDATE,
  CONSTRAINT EMPL_CAPA_PK
  PRIMARY KEY
  (EMCA_ID)
  USING INDEX VLANZ.EMPL_CAPA_PK
  ENABLE VALIDATE,
  CONSTRAINT EMCA_UK_FKS
  UNIQUE (EMCA_EMPL_ID, EMCA_CAPA_ID)
  USING INDEX VLANZ.EMCA_UK_FKS
  ENABLE VALIDATE);

ALTER TABLE VLANZ.EMPL_CAPA ADD (
  CONSTRAINT EMCA_CAPA_FK 
  FOREIGN KEY (EMCA_CAPA_ID) 
  REFERENCES VLANZ.CAPABILITIES (CAPA_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT EMCA_EMPL_FK 
  FOREIGN KEY (EMCA_EMPL_ID) 
  REFERENCES VLANZ.EMPLOYEES (EMPL_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
