ALTER TABLE VLANZ.EMPLOYEES
 DROP PRIMARY KEY CASCADE;

DROP TABLE VLANZ.EMPLOYEES CASCADE CONSTRAINTS;

CREATE TABLE VLANZ.EMPLOYEES
(
  EMPL_ID     NUMBER(10)                        NOT NULL,
  EMPL_UNAME  VARCHAR2(6 BYTE)                  NOT NULL,
  EMPL_FNAME  VARCHAR2(30 BYTE)                 NOT NULL,
  EMPL_LNAME  VARCHAR2(30 BYTE)                 NOT NULL,
  EMPL_MAIL   VARCHAR2(200 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX VLANZ.EMPLOYEE_PK ON VLANZ.EMPLOYEES
(EMPL_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE TRIGGER VLANZ.EMPL_BIUR 
before insert ON VLANZ.EMPLOYEES 
for each row
BEGIN
  :new.empl_id := nvl(:new.empl_id , empl_seq.nextval);
END;
/


ALTER TABLE VLANZ.EMPLOYEES ADD (
  CONSTRAINT EMPLOYEE_PK
  PRIMARY KEY
  (EMPL_ID)
  USING INDEX VLANZ.EMPLOYEE_PK
  ENABLE VALIDATE);
